version: '3.1'
services:
  app-pm2:
      container_name: app-pm2
      #构建容器
      build: ./node
      # 需要链接本地代码时
      ports:
        - "3000:3000"
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./www/:/var/www/html/